# Generated by Django 6.0.3 on 2026-03-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='worker_docs/certificates/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='expected_wage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='worker_docs/id_proofs/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='work_photos',
            field=models.FileField(blank=True, null=True, upload_to='worker_docs/work_photos/'),
        ),
    ]
