# Generated by Django 6.0.3 on 2026-03-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_workerprofile_certificates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='verification_note',
            field=models.TextField(blank=True, help_text='Admin notes regarding the verification status'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESUBMIT', 'Resubmit')], default='PENDING', max_length=15),
        ),
    ]
