# Generated by Django 5.2.6 on 2026-03-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_course_id_alter_coursecategory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
